name: Build Test and Package

on:
  push:    
  pull_request:
    branches: [ main ]

jobs:
  Build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore tools
      run: dotnet tool restore 
    - name: Build test and package
      run: dotnet fake run FakeBuild.fsx    
    - name: Archive Win app
      uses: actions/upload-artifact@v2
      with:
        name: benchmarkdotnet.analyser.win-x64
        path: ./publish/win-x64/*
    - name: Archive Linux app
      uses: actions/upload-artifact@v2
      with:
        name: benchmarkdotnet.analyser.linux-x64
        path: ./publish/linux-x64/*
    - name: Archive Linux Musl app
      uses: actions/upload-artifact@v2
      with:
        name: benchmarkdotnet.analyser.linux-musl-x64
        path: ./publish/linux-musl-x64/*
    - name: Archive dotnet tool nupkg
      uses: actions/upload-artifact@v2
      with:
        name: benchmarkdotnet.analyser.nupkg
        path: ./publish/toolpackage/*
    - name: Archive Test results
      uses: actions/upload-artifact@v2
      with:
        name: unittests.results
        path: ./test/BenchmarkDotNetAnalyser.Tests.Unit/TestResults/*
    - name: Archive Stryker results
      uses: actions/upload-artifact@v2
      with:
        name: stryker.results
        path: ./test/BenchmarkDotNetAnalyser.Tests.Unit/StrykerOutput/*
    - name: Unit tests
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Unit tests
        path: ${{ github.workspace }}/test/BenchmarkDotNetAnalyser.Tests.Unit/TestResults/unit_test_results.trx
        reporter: dotnet-trx
        token: ${{ secrets.GITHUB_TOKEN }}
